apiVersion: 1
groups:
    - orgId: 1
      name: ec2-monitoring
      folder: alerts
      interval: 5m
      rules:
        - uid: e254bb25-edcf-4e96-8f62-a516d43cb6df
          title: dalgo-production-ec2-ram
          condition: C
          data:
            - refId: memory_used
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: f65de527-42f9-4a12-9574-d16d4447b446
              model:
                datasource:
                    type: prometheus
                    uid: f65de527-42f9-4a12-9574-d16d4447b446
                editorMode: code
                expr: ((node_memory_MemTotal_bytes{instance="dalgo-production-ec2",job="node_exporter"} - node_memory_MemFree_bytes{instance="dalgo-production-ec2",job="node_exporter"} - (node_memory_Cached_bytes{instance="dalgo-production-ec2",job="node_exporter"} + node_memory_Buffers_bytes{instance="dalgo-production-ec2",job="node_exporter"} + node_memory_SReclaimable_bytes{instance="dalgo-production-ec2",job="node_exporter"}) + (node_memory_SwapTotal_bytes{instance="dalgo-production-ec2",job="node_exporter"} - node_memory_SwapFree_bytes{instance="dalgo-production-ec2",job="node_exporter"}) )/ (node_memory_MemTotal_bytes{instance="dalgo-production-ec2",job="node_exporter"} + node_memory_SwapTotal_bytes{instance="dalgo-production-ec2",job="node_exporter"})) * 100
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: memory_used
            - refId: B
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: memory_used
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: fd88ef15-8010-448e-9600-420226ce4297
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: fd88ef15-8010-448e-9600-420226ce4297
            __panelId__: "1"
            description: The RAM at this moment was {{ index $values "B" }}
            summary: Alerted when RAM usage exceeds 80 percent
          isPaused: false
        - uid: f66ebff2-562f-4c30-afb1-b645ec8727b2
          title: dalgo-production-ec2-cpu
          condition: C
          data:
            - refId: cpu_used
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: f65de527-42f9-4a12-9574-d16d4447b446
              model:
                datasource:
                    type: prometheus
                    uid: f65de527-42f9-4a12-9574-d16d4447b446
                editorMode: code
                exemplar: false
                expr: sum by(instance) (irate(node_cpu_seconds_total{instance="dalgo-production-ec2",job="node_exporter", mode="user"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance="dalgo-production-ec2",job="node_exporter"}[$__rate_interval]))) * 100
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: cpu_used
            - refId: B
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: cpu_used
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: fd88ef15-8010-448e-9600-420226ce4297
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: fd88ef15-8010-448e-9600-420226ce4297
            __panelId__: "1"
            description: The CPU% at this moment was {{ index $values "B" }}
            summary: Alerted when CPU usage exceeds 80 percent
          isPaused: false
        - uid: dd5b9fc9-3d6c-402c-a7c9-64ad0f36a2a1
          title: dalgo-production-ec2-disk-space
          condition: C
          data:
            - refId: disk_used
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: f65de527-42f9-4a12-9574-d16d4447b446
              model:
                datasource:
                    type: prometheus
                    uid: f65de527-42f9-4a12-9574-d16d4447b446
                editorMode: code
                expr: 100 - ((node_filesystem_avail_bytes{instance="dalgo-production-ec2",job="node_exporter",mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{instance="dalgo-production-ec2",job="node_exporter",mountpoint="/",fstype!="rootfs"})
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: disk_used
            - refId: B
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: disk_used
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: fd88ef15-8010-448e-9600-420226ce4297
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: fd88ef15-8010-448e-9600-420226ce4297
            __panelId__: "1"
            description: The Disk space at this moment was {{ index $values "B" }}
            summary: Alerted when Disk space exceeds 80 percent
          isPaused: false

deleteRules:
  - orgId: 1
    uid: e254bb25-edcf-4e96-8f62-a516d43cb6df  # ram
  - orgId: 1
    uid: f66ebff2-562f-4c30-afb1-b645ec8727b2  # cpu
  - orgId: 1
    uid: dd5b9fc9-3d6c-402c-a7c9-64ad0f36a2a1  # disk
  - orgId: 1
    uid: d6e95837-f05b-4c03-bb9c-2f37cc1e220a  # loki (legacy, may already be gone)
