global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prod_aws_ec2_instance_machine'
    static_configs:
      - targets: ['<ec2_machine_to_monitor>:<port>']
  - job_name: 'postgres_exporter'
    scrape_interval: 2s 
    static_configs:
      - targets: ['localhost:port']
  - job_name: 'ddp_backend'
    scrape_interval: 10s
    scrape_timeout: 9s
    scheme: https
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['api.dalgo.in']
