name: dalgo-prod-targets

services:
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"

  process_exporter:
    image: ncabatoff/process-exporter:0.8.7
    container_name: process_exporter
    restart: unless-stopped
    privileged: true
    command:
      - '--procfs=/host/proc'
      - '--config.path=/config/process-exporter.yml'
    volumes:
      - '/proc:/host/proc:ro'
      - ./process-exporter.yml:/config/process-exporter.yml:ro
    ports:
      - "9256:9256"

  celery_exporter:
    image: ghcr.io/danihodovic/celery-exporter:0.12.2
    container_name: celery_exporter
    restart: unless-stopped
    network_mode: host
    environment:
      CE_BROKER_URL: ${CELERY_BROKER_URL}
      CE_ACCEPT_CONTENT: json

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    command:
      - '--housekeeping_interval=30s'
      - '--global_housekeeping_interval=1m'
      - '--docker_only=true'
      - '--store_container_labels=false'
      - '--event_storage_event_limit=default=0'
      - '--event_storage_age_limit=default=0'
      - '--disable_metrics=advtcp,cpu_topology,cpuset,disk,hugetlb,memory_numa,percpu,process,referenced_memory,resctrl,sched,tcp,udp'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - "9280:8080"
    mem_limit: 512m
    memswap_limit: 512m
