apiVersion: 1

datasources:
  - name: Prometheus
    uid: f65de527-42f9-4a12-9574-d16d4447b446
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
